name: CI Cache Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Cache npm dependencies
      - name: Cache npm dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Show cache hit/miss
      - name: Show cache result
        run: |
          CACHE_HIT="${{ steps.npm-cache.outputs.cache-hit }}"
          echo "Cache hit: $CACHE_HIT"
