name: CI Cache Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Setup Node.js (for npm dependencies)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Cache npm dependencies
      - name: prime-cache-d48c5d1
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-d48c5d1
          restor
